WAL_API_KEY: 94gwe6nwuf96d67ksphxvj7a
PROS_API_KEY: df8dd3dfb7c976618cd4b5c0d0d1822a
SHOPP_API_KEY: VDaS3Z5xQRc7TERFf7e77a0176e9d21e

GMAIL_USERNAME: 'theperfectgift37@gmail.com'
GMAIL_PASSWORD: 'project2'